overrides:
  ceph:
    log-ignorelist:
      - \(SLOW_OPS\)
      - slow request
tasks:
- workunit:
    clients:
      client.0:
        - rbd/test_librbd_python.sh --eval-attr 'not (SKIP_IF_CRIMSON)'
